default:
  golem_name: PakIndicatorsApp
  golem_version: 0.0.0.9000
  app_prod: no
production:
  app_prod: yes
dev:
  golem_wd: C:/Users/wb578340/OneDrive - WBG/RShinyProjects/Pakistan_indicators/PakIndicatorsApp
